apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
   name: msk-ippool
spec:
   cidr: 192.168.1.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "MSK"

---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: krat-ippool
spec:
  cidr: 192.168.2.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "KRAT"
