apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: reactapp
  labels:
    app: reactapp
    tier: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: reactapp
  template:
    metadata:
      labels:
        tier: reactapp
    spec:
      containers:
      - name: reactapp-lab3
        image: ifilyaninitmo/itdt-contained-frontend:master
        envFrom:
          - configMapRef:
              name: reactapp-configmap
        ports:
          - containerPort: 3000